# Generated by Django 4.2.21 on 2025-05-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_earnings',
            field=models.FloatField(default=0),
        ),
    ]
