# Generated by Django 4.2.21 on 2025-05-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='total_earnings',
            field=models.FloatField(default=0),
        ),
    ]
