# Generated by Django 5.2.1 on 2025-05-18 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('shipments', '0002_city_shipment_description_shipment_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='agents.agent'),
        ),
    ]
